name: Issue
on:
  issues:
    types: [opened, edited, milestoned]
  issue_comment:
    types: [created, deleted]
jobs:
  build:
    env:
      SRC: src/github.com/${{github.repository}}
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
          JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: src/github.com/${{ github.repository }}
        # fetch-depth: 100 # support git describe --always

    - name: Unit tests
      working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
      run: |
        echo "$GITHUB_CONTEXT" | jq '.event.issue.title'
        VERSION=$(echo "$GITHUB_CONTEXT" | jq '.event.issue.title')
        echo Version: $VERSION
        # make sync package repo-index update-index
